### ISSUE TITLE
Roadmap to 1.0.0

### ISSUE THREAD

**Issue by ElForastero** [ElForastero/pulse-feed-parser#3]
- [ ] Cover parsers with unit tests
- [ ] JSON feeds support
- [ ] Support few more extensions out of the box
- [ ] Support for custom extensions
